<?php
/** Admin settings screen. @package DVLNT_Service_Area_Checker */
if ( ! defined( 'ABSPATH' ) ) { exit; }
class DVLNT_SAC_Admin {
	public static function init(){add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_enqueue_scripts',array(__CLASS__,'assets'));add_action('admin_post_dvlnt_sac_reset_appearance',array(__CLASS__,'reset_appearance'));add_action('admin_post_dvlnt_sac_clear_analytics',array(__CLASS__,'clear_analytics'));}
	public static function menu(){add_menu_page(__('Service Area Checker','dvlnt-service-area-checker'),__('Service Area Checker','dvlnt-service-area-checker'),'manage_options','dvlnt-service-area-checker',array(__CLASS__,'render'),'dashicons-location-alt',58);}
	public static function assets($hook){if('toplevel_page_dvlnt-service-area-checker'!==$hook){return;}wp_enqueue_style('wp-color-picker');wp_enqueue_style('dvlnt-sac-admin',DVLNT_SAC_URL.'assets/css/admin.css',array('wp-color-picker'),DVLNT_SAC_VERSION);wp_enqueue_script('dvlnt-sac-admin',DVLNT_SAC_URL.'assets/js/admin.js',array('wp-color-picker'),DVLNT_SAC_VERSION,true);}
	public static function reset_appearance(){if(!current_user_can('manage_options')){wp_die(esc_html__('You do not have permission to do this.','dvlnt-service-area-checker'));}check_admin_referer('dvlnt_sac_reset_appearance');$current=DVLNT_SAC_Settings::get();$defaults=DVLNT_SAC_Settings::defaults();foreach(DVLNT_SAC_Settings::appearance_keys() as $key){$current[$key]=$defaults[$key];}update_option(DVLNT_SAC_Settings::OPTION_NAME,$current);wp_safe_redirect(add_query_arg(array('page'=>'dvlnt-service-area-checker','appearance-reset'=>'1'),admin_url('admin.php')));exit;}
	public static function clear_analytics(){if(!current_user_can('manage_options')){wp_die(esc_html__('You do not have permission to do this.','dvlnt-service-area-checker'));}check_admin_referer('dvlnt_sac_clear_analytics');global $wpdb;$table=DVLNT_SAC_Analytics::table();$wpdb->query("TRUNCATE TABLE $table");wp_safe_redirect(add_query_arg(array('page'=>'dvlnt-service-area-checker','analytics-cleared'=>'1'),admin_url('admin.php')));exit;}
	private static function quick_setup(){?>
		<section class="dvlnt-sac-card dvlnt-sac-quick"><div class="dvlnt-sac-card__heading"><h2><?php esc_html_e('Quick Setup / How to Use','dvlnt-service-area-checker');?></h2><span class="dashicons dashicons-lightbulb" aria-hidden="true"></span></div><ol>
			<li><?php esc_html_e('Add the five-digit ZIP codes you serve in Service Area below, then save.','dvlnt-service-area-checker');?></li>
			<li><?php esc_html_e('Set your phone number and booking URL under Contact & Actions.','dvlnt-service-area-checker');?></li>
			<li><?php esc_html_e('Customize the existing checker text, colors, typography, and shape settings as needed.','dvlnt-service-area-checker');?></li>
			<li><?php esc_html_e('Design your trigger button normally in Brizy or another builder, then add this CSS class:','dvlnt-service-area-checker');?> <code>service-area-trigger</code></li>
			<li><?php esc_html_e('Add this shortcode once on the same page to load the checker modal:','dvlnt-service-area-checker');?> <code>[service_area_checker]</code></li>
		</ol><p class="description"><?php esc_html_e('Visitor flow: enter ZIP → see availability → use Book Service or Call Now when the ZIP is supported.','dvlnt-service-area-checker');?></p></section>
	<?php }
	private static function analytics(){
		global $wpdb;$table=DVLNT_SAC_Analytics::table();$per_page=20;$page=max(1,isset($_GET['sac_paged'])?absint($_GET['sac_paged']):1);$offset=($page-1)*$per_page;
		$allowed=array('zip'=>'zip','checks'=>'checks','supported'=>'last_supported','unsupported'=>'unsupported_checks','book'=>'book_clicks','call'=>'call_clicks','last'=>'last_checked');$orderby=isset($_GET['sac_orderby'])?sanitize_key(wp_unslash($_GET['sac_orderby'])):'';$direction=isset($_GET['sac_order'])&&'asc'===strtolower(sanitize_text_field(wp_unslash($_GET['sac_order'])))?'ASC':'DESC';
		$order_sql=isset($allowed[$orderby])?$allowed[$orderby].' '.$direction:'last_supported ASC, unsupported_checks DESC, checks DESC';
		$totals=$wpdb->get_row("SELECT COALESCE(SUM(checks),0) checks,COALESCE(SUM(supported_checks),0) supported,COALESCE(SUM(unsupported_checks),0) unsupported,COALESCE(SUM(book_clicks),0) books,COALESCE(SUM(call_clicks),0) calls,COUNT(*) zips FROM $table");
		$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table ORDER BY $order_sql LIMIT %d OFFSET %d",$per_page,$offset));$total_rows=$totals?absint($totals->zips):0;$pages=max(1,(int)ceil($total_rows/$per_page));
		$sort=function($key,$label)use($orderby,$direction){$next=$orderby===$key&&'DESC'===$direction?'asc':'desc';$url=add_query_arg(array('page'=>'dvlnt-service-area-checker','sac_orderby'=>$key,'sac_order'=>$next),admin_url('admin.php'));return '<a href="'.esc_url($url).'">'.esc_html($label).'</a>';};?>
		<section class="dvlnt-sac-card dvlnt-sac-analytics"><div class="dvlnt-sac-card__heading"><div><h2><?php esc_html_e('Analytics / Activity','dvlnt-service-area-checker');?></h2><p><?php esc_html_e('Aggregate ZIP demand and conversion activity. No personal information is collected.','dvlnt-service-area-checker');?></p></div></div>
		<div class="dvlnt-sac-metrics"><?php foreach(array('Total ZIP Checks'=>$totals->checks??0,'Supported Matches'=>$totals->supported??0,'Unsupported Checks'=>$totals->unsupported??0,'Book Clicks'=>$totals->books??0,'Call Clicks'=>$totals->calls??0)as$label=>$value):?><div><strong><?php echo esc_html(number_format_i18n((int)$value));?></strong><span><?php echo esc_html($label);?></span></div><?php endforeach;?></div>
		<h3><?php esc_html_e('Most Frequently Searched ZIP Codes','dvlnt-service-area-checker');?></h3><p class="description"><?php esc_html_e('By default, unsupported ZIPs with the most repeated searches appear first.','dvlnt-service-area-checker');?></p>
		<div class="dvlnt-sac-table-wrap"><table class="widefat striped"><thead><tr><th><?php echo $sort('zip','ZIP');?></th><th><?php echo $sort('checks','Checks');?></th><th><?php echo $sort('supported','Supported?');?></th><th><?php echo $sort('book','Book Clicks');?></th><th><?php echo $sort('call','Call Clicks');?></th><th><?php echo $sort('last','Last Checked');?></th></tr></thead><tbody><?php if($rows):foreach($rows as$row):?><tr class="<?php echo $row->last_supported?'':'dvlnt-sac-unsupported';?>"><td><code><?php echo esc_html($row->zip);?></code></td><td><strong><?php echo esc_html(number_format_i18n($row->checks));?></strong><?php if(!$row->last_supported&&$row->unsupported_checks>1):?><span class="dvlnt-sac-demand"><?php echo esc_html(sprintf(__('%s unsupported','dvlnt-service-area-checker'),number_format_i18n($row->unsupported_checks)));?></span><?php endif;?></td><td><?php echo $row->last_supported?esc_html__('Yes','dvlnt-service-area-checker'):esc_html__('No','dvlnt-service-area-checker');?></td><td><?php echo esc_html(number_format_i18n($row->book_clicks));?></td><td><?php echo esc_html(number_format_i18n($row->call_clicks));?></td><td><?php echo esc_html(get_date_from_gmt(get_gmt_from_date($row->last_checked),get_option('date_format').' '.get_option('time_format')));?></td></tr><?php endforeach;else:?><tr><td colspan="6"><?php esc_html_e('No ZIP checks recorded yet.','dvlnt-service-area-checker');?></td></tr><?php endif;?></tbody></table></div>
		<?php if($pages>1):?><div class="tablenav"><div class="tablenav-pages"><?php echo wp_kses_post(paginate_links(array('base'=>add_query_arg(array('page'=>'dvlnt-service-area-checker','sac_paged'=>'%#%','sac_orderby'=>$orderby,'sac_order'=>strtolower($direction)),admin_url('admin.php')),'format'=>'','current'=>$page,'total'=>$pages)));?></div></div><?php endif;?>
		<form action="<?php echo esc_url(admin_url('admin-post.php'));?>" method="post" class="dvlnt-sac-clear-form"><input type="hidden" name="action" value="dvlnt_sac_clear_analytics"><?php wp_nonce_field('dvlnt_sac_clear_analytics');?><button type="submit" class="button button-link-delete" data-sac-clear-analytics><?php esc_html_e('Clear / Reset Analytics','dvlnt-service-area-checker');?></button></form></section>
	<?php }
	private static function field($s,$key,$label,$type='text',$args=array()){$name=DVLNT_SAC_Settings::OPTION_NAME.'['.$key.']';$class=!empty($args['color'])?'dvlnt-sac-color':'regular-text';echo '<div class="dvlnt-sac-field"><label for="dvlnt-sac-'.esc_attr($key).'">'.esc_html($label).'</label>';if('select'===$type){echo '<select id="dvlnt-sac-'.esc_attr($key).'" name="'.esc_attr($name).'" data-preview="'.esc_attr($key).'">';foreach($args['options'] as $value=>$text){echo '<option value="'.esc_attr($value).'" '.selected($s[$key],(string)$value,false).'>'.esc_html($text).'</option>';}echo '</select>';}else{echo '<input id="dvlnt-sac-'.esc_attr($key).'" name="'.esc_attr($name).'" type="'.esc_attr($type).'" value="'.esc_attr($s[$key]).'" class="'.esc_attr($class).'" data-preview="'.esc_attr($key).'"'.(isset($args['min'])?' min="'.esc_attr($args['min']).'" max="'.esc_attr($args['max']).'"':'').'>'; }echo '</div>';}
	public static function render(){
		if(!current_user_can('manage_options')){return;}$s=DVLNT_SAC_Settings::get();
		$weights=array('400'=>'Normal (400)','500'=>'Medium (500)','600'=>'Semi-bold (600)','700'=>'Bold (700)','800'=>'Extra-bold (800)','900'=>'Black (900)');$font_names=array('Lato','Arial','Helvetica','Open Sans','Roboto','Montserrat','Poppins','Inter','system-ui');$fonts=array_combine($font_names,$font_names);
		?>
		<div class="wrap dvlnt-sac-admin"><header class="dvlnt-sac-header"><div><h1><?php esc_html_e('Service Area Checker','dvlnt-service-area-checker');?></h1><p><?php esc_html_e('Manage service coverage, modal content, and appearance.','dvlnt-service-area-checker');?></p></div><code>[service_area_checker]</code></header>
		<?php if(isset($_GET['appearance-reset'])):?><div class="notice notice-success is-dismissible"><p><?php esc_html_e('Appearance settings restored to defaults.','dvlnt-service-area-checker');?></p></div><?php endif;?>
		<?php if(isset($_GET['analytics-cleared'])):?><div class="notice notice-success is-dismissible"><p><?php esc_html_e('Analytics have been cleared.','dvlnt-service-area-checker');?></p></div><?php endif;?>
		<?php self::quick_setup();?>
		<form action="options.php" method="post" id="dvlnt-sac-settings-form"><?php settings_fields('dvlnt_sac_group');?>
		<div class="dvlnt-sac-layout"><main>
		<section class="dvlnt-sac-card"><div class="dvlnt-sac-card__heading"><h2><?php esc_html_e('Service Area','dvlnt-service-area-checker');?></h2><span id="dvlnt-sac-zip-count" class="dvlnt-sac-count"></span></div><p><?php esc_html_e('Add every five-digit ZIP code you currently serve.','dvlnt-service-area-checker');?></p><label for="dvlnt-sac-zip-codes"><strong><?php esc_html_e('ZIP Codes','dvlnt-service-area-checker');?></strong></label><textarea id="dvlnt-sac-zip-codes" name="<?php echo esc_attr(DVLNT_SAC_Settings::OPTION_NAME);?>[zip_codes]" rows="9" class="large-text code"><?php echo esc_textarea($s['zip_codes']);?></textarea><p class="description"><?php esc_html_e('Separate entries with new lines, commas, or both. Invalid entries are removed and duplicates merged when saved.','dvlnt-service-area-checker');?></p></section>
		<section class="dvlnt-sac-card"><h2><?php esc_html_e('Contact & Actions','dvlnt-service-area-checker');?></h2><p><?php esc_html_e('Set the destinations and labels shown after a successful check.','dvlnt-service-area-checker');?></p><div class="dvlnt-sac-fields"><?php self::field($s,'phone','Phone Number');self::field($s,'booking_url','Booking URL','url');self::field($s,'call_label','Call Button Label');self::field($s,'booking_label','Booking Button Label');?></div></section>
		<section class="dvlnt-sac-card"><h2><?php esc_html_e('Content','dvlnt-service-area-checker');?></h2><p><?php esc_html_e('Customize each modal state. [ZIP] inserts the submitted ZIP code.','dvlnt-service-area-checker');?></p><?php $groups=array('Initial State'=>array('initial_eyebrow'=>'Eyebrow','initial_heading'=>'Heading','initial_description'=>'Description','zip_label'=>'ZIP Label','zip_placeholder'=>'ZIP Placeholder','check_label'=>'Check Button Label'),'Success State'=>array('success_eyebrow'=>'Eyebrow','success_heading'=>'Heading','success_description'=>'Description (supports [ZIP])','success_reassurance'=>'Reassurance Text'),'Unavailable State'=>array('unavailable_eyebrow'=>'Eyebrow','unavailable_heading'=>'Heading','unavailable_description'=>'Description (supports [ZIP])','retry_label'=>'Retry Button Label'));foreach($groups as $title=>$fields):?><details class="dvlnt-sac-content" <?php echo 'Initial State'===$title?'open':'';?>><summary><?php echo esc_html($title);?></summary><div class="dvlnt-sac-fields"><?php foreach($fields as $key=>$label){self::field($s,$key,$label);}?></div></details><?php endforeach;?></section>
		<section class="dvlnt-sac-card"><h2><?php esc_html_e('Typography','dvlnt-service-area-checker');?></h2><div class="dvlnt-sac-fields"><?php self::field($s,'font_family','Font Family','select',array('options'=>$fonts));foreach(array('eyebrow_font_size'=>'Eyebrow Size','heading_size_desktop'=>'Heading Size — Desktop','heading_size_tablet'=>'Heading Size — Tablet','heading_size_mobile'=>'Heading Size — Mobile','paragraph_font_size'=>'Paragraph Size','button_font_size'=>'Button Size','label_font_size'=>'Form Label Size') as $k=>$l){self::field($s,$k,$l.' (px)','number',array('min'=>10,'max'=>72));}foreach(array('eyebrow_font_weight'=>'Eyebrow Weight','heading_font_weight'=>'Heading Weight','paragraph_font_weight'=>'Paragraph Weight','button_font_weight'=>'Button Weight','label_font_weight'=>'Form Label Weight') as $k=>$l){self::field($s,$k,$l,'select',array('options'=>$weights));}?></div></section>
		<section class="dvlnt-sac-card"><h2><?php esc_html_e('Colors','dvlnt-service-area-checker');?></h2><div class="dvlnt-sac-fields dvlnt-sac-fields--colors"><?php foreach(array('accent_color'=>'Primary Accent','heading_color'=>'Heading','body_color'=>'Body Text','eyebrow_color'=>'Eyebrow','button_background'=>'Button Background','button_text_color'=>'Button Text','input_border_color'=>'Input Border','modal_background'=>'Modal Background','modal_border_color'=>'Modal Border','overlay_color'=>'Overlay','success_color'=>'Success','error_color'=>'Error / Unavailable') as $k=>$l){self::field($s,$k,$l,'text',array('color'=>true));}?></div></section>
		<section class="dvlnt-sac-card"><h2><?php esc_html_e('Layout & Shape','dvlnt-service-area-checker');?></h2><div class="dvlnt-sac-fields"><?php foreach(array('border_radius'=>'Modal Border Radius','button_radius'=>'Button Border Radius','input_radius'=>'Input Border Radius','modal_max_width'=>'Modal Max Width','modal_padding'=>'Modal Inner Padding','button_height'=>'Button Height') as $k=>$l){self::field($s,$k,$l.' (px)','number',array('min'=>0,'max'=>800));}?></div></section>
		</main><aside><div class="dvlnt-sac-preview-card"><h2><?php esc_html_e('Preview','dvlnt-service-area-checker');?></h2><div class="dvlnt-sac-preview-wrap"><div id="dvlnt-sac-preview"><span class="preview-eyebrow"><?php echo esc_html($s['initial_eyebrow']);?></span><h3><?php echo esc_html($s['initial_heading']);?></h3><p><?php echo esc_html($s['initial_description']);?></p><label><?php echo esc_html($s['zip_label']);?></label><input disabled placeholder="<?php echo esc_attr($s['zip_placeholder']);?>"><button type="button"><?php echo esc_html($s['check_label']);?></button></div></div></div><div class="dvlnt-sac-save"><?php submit_button(__('Save Changes','dvlnt-service-area-checker'),'primary','submit',false);?><a class="button-link-delete" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=dvlnt_sac_reset_appearance'),'dvlnt_sac_reset_appearance'));?>" data-sac-reset><?php esc_html_e('Reset Appearance to Defaults','dvlnt-service-area-checker');?></a></div></aside></div></form><?php self::analytics();?></div>
		<?php
	}
}
